/*
 * @Author: james.junior
 * @Date: 6/13/23 16:26
 *
 * @Project: stocky-api
 */

package com.jamesaworo.stocky.core.constants;

public class ModulePermissions {
    // authentication
    public static final String AUTHENTICATION_ACCESS_PAGE_MANAGE_ACCOUNT = "ACCESS_PAGE_MANAGE_ACCOUNT";

    // product module permissions
    public static final String PRODUCT_ACCESS_PAGE_PRODUCT = "ACCESS_PAGE_PRODUCT";
    public static final String PRODUCT_ACCESS_ACTION_PRODUCT_SEARCH = "ACCESS_ACTION_PRODUCT_SEARCH";
    public static final String PRODUCT_ACCESS_ACTION_PRODUCT_ADD = "ACCESS_ACTION_PRODUCT_ADD";
    public static final String PRODUCT_ACCESS_ACTION_PRODUCT_UPDATE = "ACCESS_ACTION_PRODUCT_UPDATE";
    public static final String PRODUCT_ACCESS_ACTION_PRODUCT_UPLOAD = "ACCESS_ACTION_PRODUCT_UPLOAD";

    // product category permissions
    public static final String PRODUCT_CATEGORY_ACCESS_PAGE_PRODUCT_CATEGORY = "ACCESS_PAGE_PRODUCT_CATEGORY";
    public static final String PRODUCT_CATEGORY_ACCESS_ACTION_PRODUCT_CATEGORY_SEARCH = "ACCESS_ACTION_PRODUCT_CATEGORY_SEARCH";
    public static final String PRODUCT_CATEGORY_ACCESS_ACTION_PRODUCT_CATEGORY_ADD = "ACCESS_ACTION_PRODUCT_CATEGORY_ADD";
    public static final String PRODUCT_CATEGORY_ACCESS_ACTION_PRODUCT_CATEGORY_UPDATE = "ACCESS_ACTION_PRODUCT_CATEGORY_UPDATE";
    public static final String PRODUCT_CATEGORY_ACCESS_ACTION_PRODUCT_CATEGORY_UPLOAD = "ACCESS_ACTION_PRODUCT_CATEGORY_UPLOAD";

    // stock permission
    public static final String STOCK_ACCESS_PAGE_STOCK_MANAGE = "ACCESS_PAGE_STOCK_MANAGE";
    public static final String STOCK_ACCESS_ACTION_STOCK_SEARCH = "ACCESS_ACTION_STOCK_SEARCH";
    public static final String STOCK_ACCESS_ACTION_STOCK_ADD = "ACCESS_ACTION_STOCK_ADD";
    public static final String STOCK_ACCESS_ACTION_STOCK_UPDATE = "ACCESS_ACTION_STOCK_UPDATE";
    public static final String STOCK_ACCESS_ACTION_STOCK_UPLOAD = "ACCESS_ACTION_STOCK_UPLOAD";

    public static final String STOCK_COUNT_ACCESS_PAGE_COUNT_STOCK = "ACCESS_PAGE_COUNT_STOCK";
    public static final String STOCK_COUNT_ACCESS_ACTION_SEARCH_COUNT_STOCK = "ACCESS_ACTION_SEARCH_COUNT_STOCK";
    public static final String STOCK_COUNT_ACCESS_ACTION_EXPORT_COUNT_STOCK = "ACCESS_ACTION_EXPORT_COUNT_STOCK";
    public static final String STOCK_LOW_STOCK_ACCESS_PAGE_LOW_STOCK = "ACCESS_PAGE_LOW_STOCK";
    public static final String STOCK_LOW_STOCK_ACCESS_ACTION_LOW_STOCK_SEARCH = "ACCESS_ACTION_LOW_STOCK_SEARCH";
    public static final String STOCK_RECONCILE_ACCESS_PAGE_RECONCILE_STOCK = "ACCESS_PAGE_RECONCILE_STOCK";

    // stock balance
    public static final String STOCK_RECORD_STOCK_BALANCE_ACCESS_PAGE_RECORD_STOCK_BALANCE = "ACCESS_PAGE_RECORD_STOCK_BALANCE";
    public static final String STOCK_RECORD_STOCK_BALANCE_ACCESS_ACTION_RECORD_STOCK_BALANCE_SEARCH = "ACCESS_ACTION_RECORD_STOCK_BALANCE_SEARCH";
    public static final String STOCK_RECORD_STOCK_BALANCE_ACCESS_ACTION_RECORD_STOCK_BALANCE_ADD = "ACCESS_ACTION_RECORD_STOCK_BALANCE_ADD";
    public static final String STOCK_RECORD_STOCK_BALANCE_ACCESS_ACTION_RECORD_STOCK_BALANCE_UPLOAD = "ACCESS_ACTION_RECORD_STOCK_BALANCE_UPLOAD";
    public static final String STOCK_RECORD_STOCK_BALANCE_ACCESS_ACTION_RECORD_STOCK_BALANCE_UPDATE = "ACCESS_ACTION_RECORD_STOCK_BALANCE_UPDATE";


    // damaged goods
    public static final String STOCK_RECORD_DAMAGED_GOODS_ACCESS_PAGE_RECORD_DAMAGED_GOODS = "ACCESS_PAGE_RECORD_DAMAGED_GOODS";
    public static final String STOCK_RECORD_DAMAGED_GOODS_ACCESS_ACTION_RECORD_DAMAGED_GOODS_SEARCH = "ACCESS_ACTION_RECORD_DAMAGED_GOODS_SEARCH";
    public static final String STOCK_RECORD_DAMAGED_GOODS_ACCESS_ACTION_RECORD_DAMAGED_GOODS_ADD = "ACCESS_ACTION_RECORD_DAMAGED_GOODS_ADD";
    public static final String STOCK_RECORD_DAMAGED_GOODS_ACCESS_ACTION_RECORD_DAMAGED_GOODS_UPLOAD = "ACCESS_ACTION_RECORD_DAMAGED_GOODS_UPLOAD";

    public static final String STOCK_MOVE_ITEM_ACCESS_PAGE_MOVE_STOCK_ITEM = "ACCESS_PAGE_MOVE_STOCK_ITEM";
    public static final String STOCK_MOVE_ITEM_ACCESS_ACTION_MOVE_STOCK_ITEM_ADD = "ACCESS_ACTION_MOVE_STOCK_ITEM_ADD";
    public static final String STOCK_MOVE_ITEM_ACCESS_ACTION_MOVE_STOCK_ITEM_SEARCH = "ACCESS_ACTION_MOVE_STOCK_ITEM_SEARCH";
    public static final String STOCK_MOVE_ITEM_ACCESS_ACTION_MOVE_STOCK_ITEM_UPLOAD = "ACCESS_ACTION_MOVE_STOCK_ITEM_UPLOAD";

    // COMPANY
    public static final String COMPANY_BASIC_ACCESS_PAGE_COMPANY_BASIC = "ACCESS_PAGE_COMPANY_BASIC";
    public static final String COMPANY_BASIC_ACCESS_ACTION_COMPANY_BASIC_UPDATE = "ACCESS_ACTION_COMPANY_BASIC_UPDATE";

    public static final String COMPANY_TAX_ACCESS_PAGE_TAX_SETUP = "ACCESS_PAGE_TAX_SETUP";
    public static final String COMPANY_TAX_ACCESS_ACTION_TAX_SETUP_ADD = "ACCESS_ACTION_TAX_SETUP_ADD";
    public static final String COMPANY_TAX_ACCESS_ACTION_TAX_SETUP_UPDATE = "ACCESS_ACTION_TAX_SETUP_UPDATE";
    public static final String COMPANY_TAX_ACCESS_ACTION_TAX_SETUP_LIST = "ACCESS_ACTION_TAX_SETUP_LIST";

    public static final String COMPANY_UNIT_OF_MEASURE_ACCESS_PAGE = "ACCESS_PAGE_UNIT_OF_MEASURE";
    public static final String COMPANY_UNIT_OF_MEASURE_ACCESS_ACTION_ADD = "ACCESS_ACTION_UNIT_OF_MEASURE_ADD";
    public static final String COMPANY_UNIT_OF_MEASURE_ACCESS_ACTION_UPDATE = "ACCESS_ACTION_UNIT_OF_MEASURE_UPDATE";
    public static final String COMPANY_UNIT_OF_MEASURE_ACCESS_ACTION_LIST = "ACCESS_ACTION_UNIT_OF_MEASURE_LIST";

    public static final String COMPANY_PRODUCT_STATUS_ACCESS_PAGE = "ACCESS_PAGE_PRODUCT_STATUS";
    public static final String COMPANY_PRODUCT_STATUS_ACCESS_ACTION_ADD = "ACCESS_ACTION_PRODUCT_STATUS_ADD";
    public static final String COMPANY_PRODUCT_STATUS_ACCESS_ACTION_UPDATE = "ACCESS_ACTION_PRODUCT_STATUS_UPDATE";
    public static final String COMPANY_PRODUCT_STATUS_ACCESS_ACTION_LIST = "ACCESS_ACTION_PRODUCT_STATUS_LIST";

    public static final String COMPANY_PAYMENT_OPTION_ACCESS_PAGE_PAYMENT_OPTION = "ACCESS_PAGE_PAYMENT_OPTION";
    public static final String COMPANY_PAYMENT_OPTION_ACCESS_ACTION_PAYMENT_OPTION_ADD = "ACCESS_ACTION_PAYMENT_OPTION_ADD";
    public static final String COMPANY_PAYMENT_OPTION_ACCESS_ACTION_PAYMENT_OPTION_UPDATE = "ACCESS_ACTION_PAYMENT_OPTION_UPDATE";
    public static final String COMPANY_PAYMENT_OPTION_ACCESS_ACTION_PAYMENT_OPTION_LIST = "ACCESS_ACTION_PAYMENT_OPTION_LIST";

    public static final String COMPANY_LOCATION_ACCESS_PAGE_LOCATION = "ACCESS_PAGE_LOCATION";
    public static final String COMPANY_LOCATION_ACCESS_ACTION_LOCATION_ADD = "ACCESS_ACTION_LOCATION_ADD";
    public static final String COMPANY_LOCATION_ACCESS_ACTION_LOCATION_UPDATE = "ACCESS_ACTION_LOCATION_UPDATE";
    public static final String COMPANY_LOCATION_ACCESS_ACTION_LOCATION_LIST = "ACCESS_ACTION_LOCATION_LIST";

    public static final String COMPANY_EXPENSES_ACCESS_PAGE_EXPENSES = "ACCESS_PAGE_EXPENSES";
    public static final String COMPANY_EXPENSES_ACCESS_ACTION_EXPENSES_ADD = "ACCESS_ACTION_EXPENSES_ADD";
    public static final String COMPANY_EXPENSES_ACCESS_ACTION_EXPENSES_SEARCH = "ACCESS_ACTION_EXPENSES_SEARCH";
    public static final String COMPANY_EXPENSES_ACCESS_ACTION_EXPENSES_UPLOAD = "ACCESS_ACTION_EXPENSES_UPLOAD";
    public static final String COMPANY_EXPENSES_ACCESS_ACTION_EXPENSES_UPDATE = "ACCESS_ACTION_EXPENSES_UPDATE";

    // ROLE

    public static final String COMPANY_ROLE_ACCESS_PAGE_ROLE = "ACCESS_PAGE_ROLE";
    public static final String COMPANY_ROLE_ACCESS_ACTION_ROLE_ADD = "ACCESS_ACTION_ROLE_ADD";
    public static final String COMPANY_ROLE_ACCESS_ACTION_ROLE_UPDATE = "ACCESS_ACTION_ROLE_UPDATE";
    public static final String COMPANY_ROLE_ACCESS_ACTION_ROLE_LIST = "ACCESS_ACTION_ROLE_LIST";
    public static final String COMPANY_ROLE_ACCESS_ROLE_SEARCH = "ACCESS_ROLE_SEARCH";

    // CUSTOMER
    public static final String COMPANY_CUSTOMER_ACCESS_PAGE_CUSTOMER = "ACCESS_PAGE_CUSTOMER";
    public static final String COMPANY_CUSTOMER_ACCESS_ACTION_CUSTOMER_ADD = "ACCESS_ACTION_CUSTOMER_ADD";
    public static final String COMPANY_CUSTOMER_ACCESS_ACTION_CUSTOMER_UPDATE = "ACCESS_ACTION_CUSTOMER_UPDATE";
    public static final String COMPANY_CUSTOMER_ACCESS_ACTION_CUSTOMER_LIST = "ACCESS_ACTION_CUSTOMER_LIST";
    public static final String COMPANY_CUSTOMER_ACCESS_CUSTOMER_SEARCH = "ACCESS_CUSTOMER_SEARCH";

    // EMPLOYEE
    public static final String COMPANY_EMPLOYEE_ACCESS_PAGE_EMPLOYEE = "ACCESS_PAGE_EMPLOYEE";
    public static final String COMPANY_EMPLOYEE_ACCESS_ACTION_EMPLOYEE_ADD = "ACCESS_ACTION_EMPLOYEE_ADD";
    public static final String COMPANY_EMPLOYEE_ACCESS_ACTION_EMPLOYEE_UPDATE = "ACCESS_ACTION_EMPLOYEE_UPDATE";
    public static final String COMPANY_EMPLOYEE_ACCESS_ACTION_EMPLOYEE_LIST = "ACCESS_ACTION_EMPLOYEE_LIST";
    public static final String COMPANY_EMPLOYEE_ACCESS_EMPLOYEE_SEARCH = "ACCESS_EMPLOYEE_SEARCH";

    // SUPPLIER
    public static final String COMPANY_SUPPLIER_ACCESS_PAGE_SUPPLIER = "ACCESS_PAGE_SUPPLIER";
    public static final String COMPANY_SUPPLIER_ACCESS_ACTION_SUPPLIER_ADD = "ACCESS_ACTION_SUPPLIER_ADD";
    public static final String COMPANY_SUPPLIER_ACCESS_ACTION_SUPPLIER_UPDATE = "ACCESS_ACTION_SUPPLIER_UPDATE";
    public static final String COMPANY_SUPPLIER_ACCESS_ACTION_SUPPLIER_LIST = "ACCESS_ACTION_SUPPLIER_LIST";
    public static final String COMPANY_SUPPLIER_ACCESS_SUPPLIER_SEARCH = "ACCESS_SUPPLIER_SEARCH";

    // REPORT

    public static final String REPORT_ACCESS_PAGE_REPORT_SALES = "ACCESS_PAGE_REPORT_SALES";
    public static final String REPORT_ACCESS_PAGE_REPORT_EXPENSES = "ACCESS_PAGE_REPORT_EXPENSES";
    public static final String REPORT_ACCESS_PAGE_REPORT_EMPLOYEE = "ACCESS_PAGE_REPORT_EMPLOYEE";
    public static final String REPORT_ACCESS_PAGE_REPORT_CUSTOMER = "ACCESS_PAGE_REPORT_CUSTOMER";
    public static final String REPORT_ACCESS_PAGE_REPORT_STOCK = "ACCESS_PAGE_REPORT_STOCK";

    // SETTINGS

    public static final String SETTING_ACCESS_PAGE_SETTING_DASHBOARD = "ACCESS_PAGE_SETTING_DASHBOARD";
    public static final String SETTING_ACCESS_PAGE_SETTING_EXPENSES = "ACCESS_PAGE_SETTING_EXPENSES";
    public static final String SETTING_ACCESS_PAGE_SETTING_SALES = "ACCESS_PAGE_SETTING_SALES";
    public static final String SETTING_ACCESS_PAGE_SETTING_PEOPLE = "ACCESS_PAGE_SETTING_PEOPLE";
    public static final String SETTING_ACCESS_PAGE_SETTING_STOCK = "ACCESS_PAGE_SETTING_STOCK";
    public static final String SETTING_ACCESS_PAGE_SETTING_PRODUCT = "ACCESS_PAGE_SETTING_PRODUCT";

    // paywall
    public static final String PAYWALL_ACCESS_PAGE_PAYWALL_PLAN = "ACCESS_PAGE_PAYWALL_PLAN";
    public static final String PAYWALL_ACCESS_PAGE_PAYWALL_PAYMENTS = "ACCESS_PAGE_PAYWALL_PAYMENTS";
    public static final String PAYWALL_ACCESS_PAGE_PAYWALL_SETTINGS = "ACCESS_PAGE_PAYWALL_SETTINGS";
    public static final String PAYWALL_ACCESS_PAGE_PAYWALL_BILLING = "ACCESS_PAGE_PAYWALL_BILLING";
    public static final String PAYWALL_ACCESS_PAGE_PAYWALL_NOTIFICATION = "ACCESS_PAGE_PAYWALL_NOTIFICATION";

    // SALE
    public static final String SALE_ACCESS_PAGE_SALE_STORE_FRONT = "ACCESS_PAGE_SALE_STORE_FRONT";
    public static final String SALE_ACCESS_ACTION_SALE_BILL_PAYMENT = "ACCESS_ACTION_SALE_BILL_PAYMENT";
    public static final String SALE_ACCESS_ACTION_SALE_SAVE_ORDER = "ACCESS_ACTION_SALE_SAVE_ORDER";
    public static final String SALE_ACCESS_ACTION_SALE_PRINT_BILL_RECEIPT = "ACCESS_ACTION_SALE_PRINT_BILL_RECEIPT";
    public static final String SALE_ACCESS_PAGE_SALE_REFUND = "ACCESS_PAGE_SALE_REFUND";
    public static final String SALE_ACCESS_PAGE_SALE_DISCOUNT = "ACCESS_PAGE_SALE_DISCOUNT";
    public static final String SALE_ACCESS_PAGE_SALE_SHIFT_PER_DAY = "ACCESS_PAGE_SALE_SHIFT_PER_DAY";
    public static final String SALE_ACCESS_PAGE_SALE_REPRINT_RECEIPT = "ACCESS_PAGE_SALE_REPRINT_RECEIPT";

    // public static final String SALE_ACCESS_PAGE_SALE_EXCHANGE = "ACCESS_PAGE_SALE_EXCHANGE";


}
